services:
  mqtt:
    container_name: mcp4h-mqtt
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./services/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  cue-gateway:
    container_name: mcp4h-cue-gateway
    build:
      context: .
      dockerfile: services/cue-gateway/Dockerfile
    depends_on:
      - mqtt
    environment:
      - MQTT_HOST=mcp4h-mqtt
      - MQTT_PORT=1883
    ports:
      - "8080:8080"

  udp-proxy:
    container_name: mcp4h-udp-proxy
    build:
      context: .
      dockerfile: services/udp-proxy/Dockerfile
    depends_on:
      - mqtt
    environment:
      - MQTT_HOST=mcp4h-mqtt
      - MQTT_PORT=1883
    ports:
      - "20777:20777/udp"

  osc-bridge:
    container_name: mcp4h-osc-bridge
    build:
      context: .
      dockerfile: services/osc-bridge/Dockerfile
    depends_on:
      - mqtt
    environment:
      - MQTT_HOST=mcp4h-mqtt
      - MQTT_PORT=1883
    ports:
      - "9000:9000/udp"

  simhub-adapter:
    container_name: mcp4h-simhub-adapter
    build:
      context: .
      dockerfile: services/simhub-adapter/Dockerfile
    depends_on:
      - mqtt
    environment:
      - MQTT_HOST=mcp4h-mqtt
      - MQTT_PORT=1883

  voice-coach:
    container_name: mcp4h-voice-coach
    build:
      context: .
      dockerfile: services/voice-coach/Dockerfile
    depends_on:
      - mqtt
    environment:
      - MQTT_HOST=mcp4h-mqtt
      - MQTT_PORT=1883
