version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mcp4h-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"

  cue-gateway:
    build:
      context: .
      dockerfile: services/cue-gateway/Dockerfile
    container_name: mcp4h-cue-gateway
    restart: unless-stopped
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on:
      - mqtt
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace:ro

  voice-coach:
    build:
      context: .
      dockerfile: services/voice-coach/Dockerfile
    container_name: mcp4h-voice-coach
    restart: unless-stopped
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on:
      - mqtt

  osc-bridge:
    build:
      context: .
      dockerfile: services/osc-bridge/Dockerfile
    container_name: mcp4h-osc-bridge
    restart: unless-stopped
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on:
      - mqtt
    ports:
      - "9000:9000/udp"

  simhub-adapter:
    build:
      context: .
      dockerfile: services/simhub-adapter/Dockerfile
    container_name: mcp4h-simhub-adapter
    restart: unless-stopped
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on:
      - mqtt

  udp-proxy:
    build:
      context: .
      dockerfile: services/udp-proxy/Dockerfile
    container_name: mcp4h-udp-proxy
    restart: unless-stopped
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on:
      - mqtt
    ports:
      - "20777:20777/udp"
