version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto:2
    ports: ["1883:1883"]
    volumes:
      - ./services/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
  cue-gateway:
    build: ./services/cue-gateway
    depends_on: [mqtt]
    environment: ["MQTT_HOST=mqtt","MQTT_PORT=1883"]
    ports: ["8080:8080"]
  voice-coach:
    build: ./services/voice-coach
    depends_on: [mqtt]
    environment: ["MQTT_HOST=mqtt","MQTT_PORT=1883"]
  osc-bridge:
    build: ./services/osc-bridge
    depends_on: [mqtt]
    environment: ["MQTT_HOST=mqtt","MQTT_PORT=1883","OSC_HOST=host.docker.internal","OSC_PORT=9000"]
  simhub-adapter:
    build: ./services/simhub-adapter
    depends_on: [mqtt]
    environment: ["MQTT_HOST=mqtt","MQTT_PORT=1883","SIMHUB_UDP_HOST=0.0.0.0","SIMHUB_UDP_PORT=9999"]
    ports: ["9999:9999/udp"]
  udp-proxy:
    build: ./services/udp-proxy
    depends_on: [simhub-adapter]
    environment: ["GAME_UDP_HOST=0.0.0.0","GAME_UDP_PORT=20777","FORWARD_UDP_HOST=simhub-adapter","FORWARD_UDP_PORT=9999"]
    ports: ["20777:20777/udp"]
  fanatec-adapter:
    build: ./services/fanatec-adapter
    depends_on: [mqtt]
    environment: ["MQTT_HOST=mqtt","MQTT_PORT=1883","BACKEND=mock"]
