services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mcp4h-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./services/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h 127.0.0.1 -p 1883 -t '$SYS/#' -C 1 -W 2 > /dev/null || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 20

  cue-gateway:
    build:
      context: .
      dockerfile: services/cue-gateway/Dockerfile
    image: mcp4h-protocol-cue-gateway:latest
    container_name: mcp4h-cue-gateway
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on:
      mqtt:
        condition: service_healthy
    ports:
      - "8080:8080"

  udp-proxy:
    build:
      context: .
      dockerfile: services/udp-proxy/Dockerfile
    image: mcp4h-protocol-udp-proxy:latest
    container_name: mcp4h-udp-proxy
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on:
      mqtt:
        condition: service_healthy
      cue-gateway:
        condition: service_started

  osc-bridge:
    build:
      context: .
      dockerfile: services/osc-bridge/Dockerfile
    image: mcp4h-protocol-osc-bridge:latest
    container_name: mcp4h-osc-bridge
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on:
      mqtt:
        condition: service_healthy

  simhub-adapter:
    build:
      context: .
      dockerfile: services/simhub-adapter/Dockerfile
    image: mcp4h-protocol-simhub-adapter:latest
    container_name: mcp4h-simhub-adapter
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on:
      mqtt:
        condition: service_healthy

  voice-coach:
    build:
      context: .
      dockerfile: services/voice-coach/Dockerfile
    image: mcp4h-protocol-voice-coach:latest
    container_name: mcp4h-voice-coach
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on:
      mqtt:
        condition: service_healthy
